services:
  j48:
    build:
      context: .
      dockerfile: Dockerfile_weka
    container_name: j48
    command: "tail -f /dev/null"
    volumes:
      - /home/esandoval/master/RieMAE/:/app/
      - /home/Data/Datasets:/Datasets/
    working_dir: /app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
