services:
  riemae:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riemae
    command: "tail -f /dev/null"
    volumes:
      - /home/esandoval/master/RieMAE/:/app/
      - /home/esandoval/Data/:/Datasets/
    working_dir: /app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
